apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-a.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "service-a.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
