apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-b.fullname" . }}-flags
data:
  flags-{{ .Values.app.env }}.json: |-
{{ .Files.Get (printf "flags/flags-%s.json" .Values.app.env) | nindent 4 }}
